### PR TITLE
Fix/limit username char to 50/63

### LINKED ISSUE #63: Limit username to 50 characters
Limit the username to 50 chars, check SQL error code and return a custom error

### PR DESCRIPTION
**Pull request by nicolewert**
closes #63

### CODE REVIEW

File: services/UserService.go [hunk 1]
```diff
@@ -54,7 +58,11 @@ func UpdateUser(partialUpdate bool, user users.User) (*users.User, *errors.RestE
 			}
 		}
 		if user.Username != "" {
-			current.Username = user.Username
+			if err := user.UsernameValidation(); err != nil {
+				return nil, err
+			} else {
```
Comment (JiahuiChen99) [inline services/UserService.go:63]: Just a subtle comment: The else statement is not necessary since you will never reach to this part of the code if the request falls into the error part.

**Review by JiahuiChen99 — APPROVED** [review]
Good job! 👍

**Review by JiahuiChen99 — APPROVED** [review]

File: services/UserService.go (hunk 1 above)
Comment (nicolewert) [reply services/UserService.go:63]: Hm I see your point, maybe it could be refactored but if I take it out as it is, though an error displays, it is an internal service error not a bad request error like we need.
